name: test.yml
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: "auto"

      - name: Install Python dependencies
        run: uv sync --locked --group dev
      - name: Run unit tests
        run: uv run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: "auto"
      - name: Install ruff
        run: uv tool install ruff
      - name: check formatting
        run: ruff format --check pytest_django_asyncio tests
      - name: lint code
        run: ruff check pytest_django_asyncio tests
